### PR TITLE
Add NonStandardInterConceptRelationship

### PR DESCRIPTION
**Pull request by fourth44**
InterConceptRelationship can be both standard or nonstandard

### CODE REVIEW

**Comment by fourth44** [comment]
This 'replaces' InterConceptRelationship in such a way that it is no longer strictly a StandardRelationship, but a sealed trait over StandardInterConceptRelationship and NonStandardInterConceptRelationship (which is a new subcategory of NonStandardRelationship).
The only downstream breakages are where InterConceptRelationship is assumed to be strictly a StandardRelationship.
This 'fixes' the expected behaviour, in that it e.g. captures all relationships between concepts, repairing concept-relationship filters and such without code change.

**Comment by fourth44** [comment]
A slightly different solution is to not introduce a NonStandardInterConceptRelationship, but to instantiate each OtherNonStandardRelationship either as just 'OtherNonStandardRelationship' or as 'OtherNonStandardRelationship with InterConceptRelationship'. Then the class hierarchy remains essentially the same.

**Comment by dvreeze** [comment]
The reason for this pull request is indeed clear. Agreed, there should be support for querying concept-relations as described in http://www.xbrl.org/specification/conceptrelationfilters/rec-2011-10-24/conceptrelationfilters-rec-2011-10-24.html. Indeed they are not necessarily standard relationships, but can be generic relationships as well.

As for the implementation in this pull request, I see 2 issues:
* Standard inter-concept relationships no longer have direct support in the query API traits. For example, trait PresentationRelationshipContainerLike depends on query methods in trait InterConceptRelationshipContainerApi, expecting the latter to offer standard inter-concept relationship querying. More generally, the notion of standard inter-concept relationships (P-, D- or C-relationships) is so fundamental to TQA that it must not get lost in any way, including in the query API traits.
* When instantiating classes in the relationship type hierarchy we use no substitution group mapping as context. Therefore we do not even know about generic relationships, but call them non-standard relationships. Something similar is true for inter-concept relationships (whether generic or standard): we do not know if the relationship source and target are concept declarations. We only know that they are global element declarations. The query API trait does know, but relationship bootstrapping does not. So a rather general notion of "inter-concept relationships" does not exist without substitution group knowledge, whereas such a notion of "inter-element-declaration relationships" does exist.

I do agree that standard interconcept relationships should be named as such. This must be done throughout TQA, and will affect many source files, although the impact on the public API is manageable. Then, and only then, should support be created for querying (standard or generic) "concept relations". I'm going to work on that now.

**Comment by fourth44** [comment]
As for the query api, I can understand these are primarily targeted at supporting the various standard inter-concept relationships (most notably dimensional relationships), and wouldn't make much sense in the realm of 'non-standard inter-concept relationships'. Hence I understand the renaming throughout.

As for InterConceptRelationshipPath, I believe precisely these are being used for computing the ConceptRelation filter (inuit). Then the choice here is to either keep this limited to standard inter-concept relationships (as it is now) or broaden it to be useful for a new umbrella inter-concept relationship trait. Either way, as long as such an umbrella trait exists, downstream users of TQA could copy-paste InterConceptRelationshipPath and adapt for the ubrella trait (although I would argue that such a feature should live in TQA itself).

As for not knowing whether a non-standard inter-concept relationship truly is between concepts (using substitution group knowledge) or just left as a inter-globalelementdeclaration relationship - the latter might be sufficient for all practical purposes. As long as there is a trait that captures all inter-globalelementdeclaration relationships.

**Comment by dvreeze** [comment]
Both standard inter-concept relationships and standard/generic inter-concept relationships are first class citizens now in TQA (since the latest commits). That is true for the relationship types, query API traits and "relationship paths". Indeed, both notions of inter-concept relationships "stand their ground" in terms of XBRL specifications that describe them (without using these terms).

Another reason for supporting both types of inter-concept relationships and not doing away with the query API traits for standard inter-concept relationships is the fact that standard inter-concept relationships can be created more efficiently than non-standard inter-concept relationships. For the former category we know that the relationship source and target must both be concept declarations, that is, global element declarations directly or indirectly in the xbrli:item of xbrli:tuple substitution groups. For generic relationships between global element declarations we do not know upfront that the relationship source and target are concepts. Hence non-standard inter-concept relationships are less efficient than standard inter-concept relationships. Again, both notions of inter-concept relationships are important enough to want to support them well in TQA.

In the query API traits for both categories of inter-concept relationships there is a lot of code repetition. An alternative would be to make standard inter-concept relationship querying depend on "general" inter-concept relationship querying, at least in the implementation. I chose not to do so for now.

**Comment by dvreeze** [comment]
Johan Walters, thanks for your pull request. I now made both the standard inter-concept relationships and the standard/generic inter-concept relationships of your pull request first-class citizens of TQA. That means that the code of the pull request is not merged, but the result is still heavily inspired by it. I am about to release TQA 0.9.0, thus solving the bug in XBRL formula and table processing that inter-concept relationships could so far only be standard ones. This would not have been the case without your pull request.

**Pull request closed without merging**
